#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Glue Installer', '1.0.0');
$app->add(new Glue\Installer\Console\InitCommand);
$app->add(new Glue\Installer\Console\InstallCommand);
$app->add(new Glue\Installer\Console\NamespaceCommand);

$app->run();
